name: build

# Add the following dependencies:
# dev_dependencies:
#   analyzer: ^0.41.2
#   dart_code_metrics: ^2.4.0
#   flutter_test:
#     sdk: flutter
#   integration_test:
#     sdk: flutter
#   pedantic: ^1.9.0

on:
  push:
    branches:
      - main
      - checkmycode
      - rem-dupes

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - run: npm install -g jscpd

      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"

      # Setup the flutter environment.
      - uses: actions/checkout@v2
        with:
          checkout_dir: $GITHUB_WORKSPACE
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable" # 'dev', 'alpha', default to: 'stable'
          # flutter-version: '1.12.x' # you can also specify exact version of flutter

      # Get flutter dependencies.
      - run: flutter pub get

      - uses: actions/checkout@v2
      - name: run checkmycode
        run: |
          chmod +x ./checkmycode.sh
          ./checkmycode.sh
        shell: bash

      # Check for any formatting issues in the code.
      - run: |
          flutter format --set-exit-if-changed .
          flutter analyze
          flutter pub global run dart_code_metrics:metrics lib  -r html --cyclomatic-complexity=3 --lines-of-executable-code=5 --number-of-arguments=2 --number-of-methods=2 --maximum-nesting=2

      # Build apk.
      - run: flutter build apk

      # Upload generated apk to the artifacts.
      - uses: actions/upload-artifact@v1
        with:
          name: release-apk
          path: build/app/outputs/apk/release/app-release.apk